spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 15
      min-idle: 5
      max-wait: 50000
  redis:
    host:
    port:
    password:
    timeout: 10000
    lettuce:
      pool:
        max-wait: 10000
  elasticsearch:
    uris:

server:
  port: 8080
