spring:
  mail:
    host: smtp.163.com
    username: zxldewyyx@163.com
    password: YGDYWNUSFJUMDWSS
    port: 25
  datasource:
    url: jdbc:mysql://114.215.41.41:3306/mm_er?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: madeinheaven
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 114.215.41.41
    port: 6379
    password: nianta0121..
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 30000
        min-idle: 0

server:
  port: 80

logging:
  level:
    root: warn